name: SSH
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1

     - name: Try Build
       run: ./not-exist-file.sh it bloke build

     - name: Start SSH via Ngrok
       if: ${{ failure() }}
       run: curl -sL https://proxy.xiaofeiya.tk/debug-github-actions.sh | bash
       env:
        NGROK_TOKEN: 1pjWdwBy83ubnvUVEDmGHVNSE88_4fRFHPBUKh82N8E7RH7Ce
        USER_PASS: xiaolan
     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 24h
